"""
构建脚本 - 生成 PyInstaller 可执行文件 + 版本信息

版本来源优先级：环境变量 MY_TYPELESS_VERSION > --version 参数 > 不写入（运行时回落 0.0.0.dev0）

CI 通过环境变量传入版本，脚本生成 src/my_typeless/_version.py（gitignored），
源树中的 version.py 永远保持为 dev fallback。

用法:
  MY_TYPELESS_VERSION=1.2.3 python scripts/build.py --no-build
  python scripts/build.py --version 1.2.3
"""

import argparse
import os
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BUILD_VERSION_FILE = ROOT / "src" / "my_typeless" / "_version.py"
SPEC_FILE = ROOT / "my_typeless.spec"
VERSION_INFO_FILE = ROOT / "file_version_info.txt"
RESOURCES_DIR = ROOT / "src" / "my_typeless" / "resources"

DEV_VERSION = "0.0.0.dev0"
ENV_VERSION_KEY = "MY_TYPELESS_VERSION"


def _normalize_version(version: str) -> str:
    """去掉可能的 'v'/'V' 前缀，兼容 'v1.2.3' 与 '1.2.3' 两种写法"""
    if not version:
        raise ValueError("version must be a non-empty string")
    normalized = version.lstrip("vV")
    if not normalized:
        raise ValueError(f"version contains only 'v' prefix: {version!r}")
    return normalized


def write_build_version(version: str) -> None:
    """生成 _version.py 注入实际版本（CI/构建流程使用，源树 version.py 不变）"""
    BUILD_VERSION_FILE.write_text(
        '"""Auto-generated by scripts/build.py at build time — do not edit, do not commit."""\n\n'
        f'__version__ = "{version}"\n',
        encoding="utf-8",
    )
    print(f"[build] {BUILD_VERSION_FILE.name} written with {version}")


def generate_version_info(version: str) -> None:
    """生成 Windows 版本信息文件"""
    version = _normalize_version(version)
    base_version = re.split(r"[-+]", version, maxsplit=1)[0]
    # 取前导的数字段（兼容 PEP 440 的 .dev0/.a1/.rc1 等后缀）
    parts: list[int] = []
    for seg in base_version.split("."):
        if not seg.isdigit():
            break
        parts.append(int(seg))
    while len(parts) < 4:
        parts.append(0)
    major, minor, patch, build = parts[:4]

    info = f"""\
# UTF-8
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers=({major}, {minor}, {patch}, {build}),
    prodvers=({major}, {minor}, {patch}, {build}),
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0),
  ),
  kids=[
    StringFileInfo([
      StringTable(
        '040904B0',
        [
          StringStruct('CompanyName', 'xbghc'),
          StringStruct('FileDescription', 'My Typeless - AI Voice Dictation'),
          StringStruct('FileVersion', '{version}'),
          StringStruct('InternalName', 'MyTypeless'),
          StringStruct('OriginalFilename', 'MyTypeless.exe'),
          StringStruct('ProductName', 'My Typeless'),
          StringStruct('ProductVersion', '{version}'),
        ],
      )
    ]),
    VarFileInfo([VarStruct('Translation', [0x0409, 1200])])
  ],
)
"""
    VERSION_INFO_FILE.write_text(info, encoding="utf-8")
    print(f"[build] Version info file generated: {VERSION_INFO_FILE}")


def generate_ico() -> None:
    """从 app_icon.svg 生成包含多分辨率层的 app_icon.ico（委托到共享模块）"""
    sys.path.insert(0, str(ROOT / "src"))
    from my_typeless.icon_builder import ICO_PATH, ensure_app_ico

    result = ensure_app_ico()
    if result is None and not ICO_PATH.exists():
        print(
            "[build] ERROR: ICO generation failed (needs resvg_py + Pillow)",
            file=sys.stderr,
        )
        sys.exit(1)
    print(f"[build] ICO ready: {ICO_PATH}")


def generate_tray_pngs() -> None:
    """从 SVG 生成托盘图标 PNG（pystray 使用 Pillow Image，需要 PNG 格式）"""
    tray_icons = ["icon_idle", "icon_recording", "icon_processing"]
    try:
        import resvg_py
    except ImportError:
        # 检查 PNG 是否已存在
        all_exist = all((RESOURCES_DIR / f"{name}.png").exists() for name in tray_icons)
        if all_exist:
            print("[build] resvg_py not installed, using existing PNG files")
            return
        print("[build] WARNING: resvg_py not installed, cannot generate tray PNGs", file=sys.stderr)
        return

    size = 64
    for name in tray_icons:
        svg_path = RESOURCES_DIR / f"{name}.svg"
        png_path = RESOURCES_DIR / f"{name}.png"
        if not svg_path.exists():
            print(f"[build] SVG not found: {svg_path}, skipping")
            continue
        png_data = bytes(resvg_py.svg_to_bytes(svg_path=str(svg_path), width=size, height=size))
        png_path.write_bytes(png_data)

    print(f"[build] Tray PNGs generated: {', '.join(tray_icons)}")


def run_pyinstaller() -> None:
    """执行 PyInstaller 构建"""
    cmd = [
        sys.executable,
        "-m",
        "PyInstaller",
        str(SPEC_FILE),
        "--clean",
        "--noconfirm",
    ]
    print(f"[build] Running: {' '.join(cmd)}")
    result = subprocess.run(cmd, cwd=str(ROOT))
    if result.returncode != 0:
        print("[build] PyInstaller build failed!", file=sys.stderr)
        sys.exit(1)
    print("[build] Build completed successfully!")
    print(f"[build] Output: {ROOT / 'dist' / 'MyTypeless.exe'}")


def resolve_version(arg_version: str | None) -> tuple[str, str | None]:
    """返回 (version, source). source 为 None 表示走 dev fallback，不写 _version.py"""
    env_version = os.environ.get(ENV_VERSION_KEY)
    if env_version:
        return _normalize_version(env_version), f"env {ENV_VERSION_KEY}"
    if arg_version:
        return _normalize_version(arg_version), "--version arg"
    return DEV_VERSION, None


def main():
    parser = argparse.ArgumentParser(description="Build My Typeless executable")
    parser.add_argument(
        "--version",
        "-v",
        help=f"Set version before building (e.g. 1.2.0). Overridden by ${ENV_VERSION_KEY} if set.",
    )
    parser.add_argument(
        "--no-build",
        action="store_true",
        help="Only prepare version + assets, skip PyInstaller build",
    )
    args = parser.parse_args()

    version, source = resolve_version(args.version)
    if source is not None:
        write_build_version(version)
        print(f"[build] Building version {version} (from {source})")
    else:
        print(f"[build] No version specified; using dev fallback {version} (no _version.py written)")

    generate_version_info(version)
    generate_ico()
    generate_tray_pngs()

    if not args.no_build:
        run_pyinstaller()


if __name__ == "__main__":
    main()
